### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/recipes-rb#7]
Once these are all done, I will be satisfied enough to put a PR for `dev` branch, and an actual release.
## Parsers
- [x] ShapedOreRecipe
- [ ] ShapelessOreRecipe
- [ ] ShapedRecipe
- [ ] ShapelessRecipe
- [ ] Furnace recipes
## General
- [ ] CLI utility installable through RubyGems.
  - This would allow us to quickly do tasks like `ftb-recipes --merge Cg -with Cg1` or `ftb-recipes --parse <code>` or `ftb-recipes --file recipes.yml`
  - Option `-p` to print the output
  - Option `-out filename.txt` to print the output to this file
- [ ] Configurable file that would basically instruct the program to do certain things. My thinking is we could do this with YAML, with specific keys for certain tasks. Example

``` yaml
parse: GameRegistry.addRecipe(new ShapedOreRecipe(Items.bucket, "oao", "aoa", 'o', "ingotIron", 'a', "nuggetGold"));
parse: GameRegistry.addRecipe(new ShapedOreRecipe(Items.bucket, "oao", "aoa", 'o', "ingotIron", 'a', "nuggetIron"));
merge:
  - {{Cg/Crafting Table|A1={{O|one}}|O={{Gc|mod=V|dis=false|Output}}}}
  - {{Cg/Crafting Table|A1={{O|two}}|O={{Gc|mod=V|dis=false|Output}}}}
```
